{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fluentd-helm.serviceAccountName" . }}
  labels:
{{ include "fluentd-helm.labels" . | indent 4 }}
{{- end -}}
