apiVersion: v1
description: Official Elastic helm chart for Elasticsearch
home: https://github.com/elastic/helm-charts
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: es-helm
sources:
  - https://github.com/elastic/elasticsearch
